FROM index.alauda.cn/alauda/hello-world:latest
LABEL Version="1.1.90790790711ayyy"
RUN sleep 1 && touch /tmp/aadf.txt && echo "aaa at Dockerfile" >>aadf.txt
RUN sleep 1 && touch /tmp/bbdf.txt && echo "bbb at Dockerfile" >>bbdf.txt